#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/rancher-ecr-credentials .
docker build -t ${REPO}/rancher-ecr-credentials:${TAG} .

echo Built ${REPO}/rancher-ecr-credentials:${TAG}
